# Generated by Django 2.0.3 on 2018-05-01 04:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_management', '0028_auto_20180424_2317'),
    ]

    operations = [
    ]
