# Generated by Django 2.0.3 on 2018-05-01 04:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
