# Generated by Django 2.0.3 on 2018-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicomponent',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
