# Generated by Django 2.0.3 on 2018-04-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20180430_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
