# Generated by Django 2.0.1 on 2018-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=512)),
                ('description', models.TextField(max_length=2048)),
                ('website', models.URLField(max_length=512)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=20)),
                ('key_employees', models.TextField(max_length=4096)),
                ('logo_url', models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=256)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
    ]
