# Generated by Django 2.0.3 on 2018-04-11 02:23

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=2048)),
                ('website', models.URLField(max_length=512)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('key_employees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None)),
                ('logo_file', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='services',
            field=models.ManyToManyField(related_name='organizations', to='organization_management.Service'),
        ),
    ]
