# Generated by Django 2.0.3 on 2018-04-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
