# Generated by Django 2.0.3 on 2018-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0002_auto_20180330_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
