# Generated by Django 2.0.3 on 2018-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0004_auto_20180330_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='services',
            field=models.ManyToManyField(related_name='organizations', to='organization_management.Service'),
        ),
    ]
