# Generated by Django 2.0.3 on 2018-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0005_organization_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(default='none@none.com', max_length=254),
            preserve_default=False,
        ),
    ]
