# Generated by Django 2.0.3 on 2018-04-04 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0006_organization_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='key_employees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None),
        ),
    ]
