# Generated by Django 2.0.3 on 2018-04-04 11:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0007_auto_20180404_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
