# Generated by Django 2.0.3 on 2018-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0008_auto_20180404_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
