# Generated by Django 2.0.3 on 2018-04-19 03:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0012_auto_20180417_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='services_other',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='branch',
            name='key_employees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None),
        ),
    ]
