# Generated by Django 2.0.3 on 2018-04-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0014_auto_20180419_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, help_text='Must be smaller than 10MB.', null=True, upload_to=''),
        ),
    ]
