# Generated by Django 2.0.3 on 2018-04-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0015_organization_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
