# Generated by Django 2.0.3 on 2018-04-19 12:42

from django.db import migrations, models


def define_languages(apps, schema_editor):
    Language = apps.get_model('organization_management', 'Language')
    LANGUAGES = [
        'English',
        'Spanish',
        'Arabic',
        'Burmese',
        'Nepali',
        'Vietnamese',
        'Persian',
    ]
    for language in LANGUAGES:
        lang = Language()
        lang.name = language
        lang.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0016_auto_20180419_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='languages',
            field=models.ManyToManyField(
                to='organization_management.Language'),
        ),
        migrations.RunPython(define_languages),
    ]
