# Generated by Django 2.0.3 on 2018-04-22 13:43

from django.db import migrations, models


def define_training_programs(apps, schema_editor):
    TrainingProgram = apps.get_model(
        'organization_management', 'TrainingProgram')
    PROGRAMS = [
        'Digital literacy training',
        'Certifications and skills based instruction',
        'English as a second language',
        'General Education Development (GED)',
        'Adult basic education',
        'Financial literacy',
        'Health literacy',
        'Job assistance',
    ]
    for program in PROGRAMS:
        training_program = TrainingProgram()
        training_program.name = program
        training_program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0017_auto_20180419_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='lab_machine_count',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Number of lab machines'),
        ),
        migrations.AddField(
            model_name='branch',
            name='public_access',
            field=models.CharField(
                blank=True, default='Yes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='training_programs',
            field=models.ManyToManyField(
                to='organization_management.TrainingProgram'),
        ),
        migrations.RunPython(define_training_programs),
    ]
