# Generated by Django 2.0.3 on 2018-04-22 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0018_auto_20180422_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='lab_machine_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of lab machines'),
        ),
    ]
