# Generated by Django 2.0.3 on 2018-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0019_auto_20180422_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='languages',
            field=models.ManyToManyField(blank=True, to='organization_management.Language'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organization_management.Service'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='training_programs',
            field=models.ManyToManyField(blank=True, to='organization_management.TrainingProgram'),
        ),
    ]
