# Generated by Django 2.0.3 on 2018-04-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0022_auto_20180422_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ('branch__organization__name', 'branch__address', 'weekday', 'from_hour'), 'verbose_name_plural': 'Opening Hours'},
        ),
    ]
