# Generated by Django 2.0.3 on 2018-04-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0016_auto_20180423_0037'),
        ('organization_management', '0023_auto_20180422_1004'),
    ]

    operations = [
    ]
