# Generated by Django 2.0.3 on 2018-04-25 01:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0024_merge_20180424_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
