# Generated by Django 2.0.3 on 2018-04-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0025_auto_20180424_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
