# Generated by Django 2.0.3 on 2018-04-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0027_auto_20180424_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
