# Generated by Django 2.0.3 on 2018-04-19 12:42

from django.db import migrations, models
import os

def define_orgs(apps, schema_editor):
    os.system("python load_test_data.py < 2016_Community_Digital_Training_Resources.csv")

class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0028_auto_20180424_2317'),
    ]

    operations = [
        migrations.RunPython(define_orgs, reverse_code=migrations.RunPython.noop),
    ]
