# Generated by Django 2.0.3 on 2018-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0030_activationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='key',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
