# Generated by Django 2.0.3 on 2018-05-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0031_auto_20180501_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationtoken',
            old_name='key',
            new_name='token',
        ),
    ]
