# Generated by Django 2.0.3 on 2018-05-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0032_auto_20180501_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
