# Generated by Django 2.0.3 on 2018-04-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_management', '0002_auto_20180411_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('time', models.DateTimeField()),
                ('description', models.TextField(max_length=5096)),
                ('mask_profile', models.BooleanField(default=False)),
                ('contact_name', models.CharField(max_length=256)),
                ('organization', models.ForeignKey(on_delete='CASCADE', related_name='events', to='organization_management.Organization')),
            ],
        ),
    ]
